### PR TITLE
chore(data): refactor key & emoji data

### PR DESCRIPTION
**Pull request by tknickman**
Awesome app! This PR refactors the data (key and emoji's) to make it more modular, scalable, and testable. This should make it much easier for this app to support many languages without causing the main app `index.js` file to grow extremely large.

Let me know what you think!

### CODE REVIEW

**Comment by ericadamski** [comment]
Awesome thanks!

**Comment by ericadamski** [comment]
I loved what you have done! After merging a few PRs I have created some conflicts with this, would you mind resolving them so I can merge this 😄 

Thank you again for the awesome contribution!

**Comment by tknickman** [comment]
@ericadamski absolutely, I'll take a look at the merge conflicts this morning and ping you when this is good to go!

**Comment by tknickman** [comment]
Updated!

**Comment by ericadamski** [comment]
Awesome thank you!

**Pull request merged**
